import db from "..";
import { advocates } from "../schema";

const specialties = [
  "Bipolar",
  "LGBTQ",
  "Medication/Prescribing",
  "Suicide History/Attempts",
  "General Mental Health (anxiety, depression, stress, grief, life transitions)",
  "Men's issues",
  "Relationship Issues (family, friends, couple, etc)",
  "Trauma & PTSD",
  "Personality disorders",
  "Personal growth",
  "Substance use/abuse",
  "Pediatrics",
  "Women's issues (post-partum, infertility, family planning)",
  "Chronic pain",
  "Weight loss & nutrition",
  "Eating disorders",
  "Diabetic Diet and nutrition",
  "Coaching (leadership, career, academic and wellness)",
  "Life coaching",
  "Obsessive-compulsive disorders",
  "Neuropsychological evaluations & testing (ADHD testing)",
  "Attention and Hyperactivity (ADHD)",
  "Sleep issues",
  "Schizophrenia and psychotic disorders",
  "Learning disorders",
  "Domestic abuse",
];

const randomSpecialty = () => {
  const random1 = Math.floor(Math.random() * 24);
  const random2 = Math.floor(Math.random() * (24 - random1)) + random1 + 1;

  return [random1, random2];
};

const advocateData = [
  {
    id: 1,
    firstName: "Benjamin",
    lastName: "Clark",
    city: "Seattle",
    degree: "MA",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 10,
    phoneNumber: 5551234567,
  },
  {
    id: 2,
    firstName: "Jane",
    lastName: "Smith",
    city: "Los Angeles",
    degree: "PhD",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 8,
    phoneNumber: 5559876543,
  },
  {
    id: 3,
    firstName: "Alice",
    lastName: "Johnson",
    city: "Chicago",
    degree: "MSW",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 5,
    phoneNumber: 5554567890,
  },
  {
    id: 4,
    firstName: "Michael",
    lastName: "Brown",
    city: "Houston",
    degree: "MD",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 12,
    phoneNumber: 5556543210,
  },
  {
    id: 5,
    firstName: "Emily",
    lastName: "Davis",
    city: "Phoenix",
    degree: "PhD",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 7,
    phoneNumber: 5553210987,
  },
  {
    id: 6,
    firstName: "Chris",
    lastName: "Martinez",
    city: "Philadelphia",
    degree: "MSW",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 9,
    phoneNumber: 5557890123,
  },
  {
    id: 7,
    firstName: "Jessica",
    lastName: "Taylor",
    city: "San Antonio",
    degree: "MD",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 11,
    phoneNumber: 5554561234,
  },
  {
    id: 8,
    firstName: "David",
    lastName: "Harris",
    city: "San Diego",
    degree: "PhD",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 6,
    phoneNumber: 5557896543,
  },
  {
    id: 9,
    firstName: "Laura",
    lastName: "Clark",
    city: "Dallas",
    degree: "MSW",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 4,
    phoneNumber: 5550123456,
  },
  {
    id: 10,
    firstName: "Daniel",
    lastName: "Lewis",
    city: "San Jose",
    degree: "MD",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 13,
    phoneNumber: 5553217654,
  },
  {
    id: 11,
    firstName: "Sarah",
    lastName: "Lee",
    city: "Austin",
    degree: "PhD",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 10,
    phoneNumber: 5551238765,
  },
  {
    id: 12,
    firstName: "James",
    lastName: "King",
    city: "Jacksonville",
    degree: "MSW",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 5,
    phoneNumber: 5556540987,
  },
  {
    id: 13,
    firstName: "Megan",
    lastName: "Green",
    city: "San Francisco",
    degree: "MD",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 14,
    phoneNumber: 5559873456,
  },
  {
    id: 14,
    firstName: "Joshua",
    lastName: "Walker",
    city: "Columbus",
    degree: "PhD",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 9,
    phoneNumber: 5556781234,
  },
  {
    id: 15,
    firstName: "Amanda",
    lastName: "Hall",
    city: "Fort Worth",
    degree: "MSW",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 3,
    phoneNumber: 5559872345,
  },
  {
    id: 16,
    firstName: "Robert",
    lastName: "Anderson",
    city: "Charlotte",
    degree: "PhD",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 15,
    phoneNumber: 5551234890,
  },
  {
    id: 17,
    firstName: "Lisa",
    lastName: "Thompson",
    city: "Detroit",
    degree: "MSW",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 7,
    phoneNumber: 5559876012,
  },
  {
    id: 18,
    firstName: "Mark",
    lastName: "Wilson",
    city: "Memphis",
    degree: "MD",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 18,
    phoneNumber: 5556543789,
  },
  {
    id: 19,
    firstName: "Rachel",
    lastName: "Garcia",
    city: "Boston",
    degree: "MA",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 4,
    phoneNumber: 5553210456,
  },
  {
    id: 20,
    firstName: "Kevin",
    lastName: "Miller",
    city: "Nashville",
    degree: "PhD",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 12,
    phoneNumber: 5557890654,
  },
  {
    id: 21,
    firstName: "Nicole",
    lastName: "Rodriguez",
    city: "Denver",
    degree: "MSW",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 6,
    phoneNumber: 5554567123,
  },
  {
    id: 22,
    firstName: "Brian",
    lastName: "Martinez",
    city: "Portland",
    degree: "MD",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 9,
    phoneNumber: 5551237890,
  },
  {
    id: 23,
    firstName: "Stephanie",
    lastName: "Young",
    city: "Las Vegas",
    degree: "PhD",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 11,
    phoneNumber: 5556789012,
  },
  {
    id: 24,
    firstName: "Andrew",
    lastName: "Davis",
    city: "Oklahoma City",
    degree: "MSW",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 5,
    phoneNumber: 5559012345,
  },
  {
    id: 25,
    firstName: "Maria",
    lastName: "Hernandez",
    city: "Louisville",
    degree: "MA",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 8,
    phoneNumber: 5552345678,
  },
  {
    id: 26,
    firstName: "Patrick",
    lastName: "Moore",
    city: "Baltimore",
    degree: "PhD",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 16,
    phoneNumber: 5555678901,
  },
  {
    id: 27,
    firstName: "Jennifer",
    lastName: "Jackson",
    city: "Milwaukee",
    degree: "MSW",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 3,
    phoneNumber: 5558901234,
  },
  {
    id: 28,
    firstName: "Ryan",
    lastName: "Thomas",
    city: "Albuquerque",
    degree: "MD",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 13,
    phoneNumber: 5551234567,
  },
  {
    id: 29,
    firstName: "Kimberly",
    lastName: "White",
    city: "Tucson",
    degree: "PhD",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 10,
    phoneNumber: 5554567890,
  },
  {
    id: 30,
    firstName: "Jason",
    lastName: "Harris",
    city: "Fresno",
    degree: "MSW",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 7,
    phoneNumber: 5557890123,
  },
  {
    id: 31,
    firstName: "Michelle",
    lastName: "Clark",
    city: "Sacramento",
    degree: "MA",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 4,
    phoneNumber: 5550123456,
  },
  {
    id: 32,
    firstName: "Tyler",
    lastName: "Lewis",
    city: "Long Beach",
    degree: "PhD",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 14,
    phoneNumber: 5553456789,
  },
  {
    id: 33,
    firstName: "Angela",
    lastName: "Robinson",
    city: "Kansas City",
    degree: "MSW",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 9,
    phoneNumber: 5556789012,
  },
  {
    id: 34,
    firstName: "Jonathan",
    lastName: "Walker",
    city: "Mesa",
    degree: "MD",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 17,
    phoneNumber: 5559012345,
  },
  {
    id: 35,
    firstName: "Samantha",
    lastName: "Hall",
    city: "Atlanta",
    degree: "PhD",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 6,
    phoneNumber: 5552345678,
  },
  {
    id: 36,
    firstName: "Christopher",
    lastName: "Allen",
    city: "Colorado Springs",
    degree: "MSW",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 11,
    phoneNumber: 5555678901,
  },
  {
    id: 37,
    firstName: "Ashley",
    lastName: "Young",
    city: "Omaha",
    degree: "MA",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 5,
    phoneNumber: 5558901234,
  },
  {
    id: 38,
    firstName: "Matthew",
    lastName: "King",
    city: "Raleigh",
    degree: "PhD",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 12,
    phoneNumber: 5551234890,
  },
  {
    id: 39,
    firstName: "Heather",
    lastName: "Wright",
    city: "Miami",
    degree: "MSW",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 8,
    phoneNumber: 5554567123,
  },
  {
    id: 40,
    firstName: "Nicholas",
    lastName: "Lopez",
    city: "Oakland",
    degree: "MD",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 19,
    phoneNumber: 5557890456,
  },
  {
    id: 41,
    firstName: "Amanda",
    lastName: "Hill",
    city: "Minneapolis",
    degree: "PhD",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 7,
    phoneNumber: 5550123789,
  },
  {
    id: 42,
    firstName: "Gregory",
    lastName: "Scott",
    city: "Tulsa",
    degree: "MSW",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 4,
    phoneNumber: 5553456012,
  },
  {
    id: 43,
    firstName: "Melissa",
    lastName: "Green",
    city: "Cleveland",
    degree: "MA",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 13,
    phoneNumber: 5556789345,
  },
  {
    id: 44,
    firstName: "Adam",
    lastName: "Adams",
    city: "Wichita",
    degree: "PhD",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 10,
    phoneNumber: 5559012678,
  },
  {
    id: 45,
    firstName: "Katherine",
    lastName: "Baker",
    city: "New Orleans",
    degree: "MSW",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 6,
    phoneNumber: 5552345901,
  },
  {
    id: 46,
    firstName: "Eric",
    lastName: "Gonzalez",
    city: "Arlington",
    degree: "MD",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 15,
    phoneNumber: 5555678234,
  },
  {
    id: 47,
    firstName: "Brittany",
    lastName: "Nelson",
    city: "Tampa",
    degree: "PhD",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 9,
    phoneNumber: 5558901567,
  },
  {
    id: 48,
    firstName: "Steven",
    lastName: "Carter",
    city: "Honolulu",
    degree: "MSW",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 5,
    phoneNumber: 5551234802,
  },
  {
    id: 49,
    firstName: "Diana",
    lastName: "Mitchell",
    city: "Anaheim",
    degree: "MA",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 11,
    phoneNumber: 5554567135,
  },
  {
    id: 50,
    firstName: "Benjamin",
    lastName: "Perez",
    city: "Aurora",
    degree: "PhD",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 8,
    phoneNumber: 5557890468,
  },
  {
    id: 51,
    firstName: "Lauren",
    lastName: "Roberts",
    city: "Santa Ana",
    degree: "MSW",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 12,
    phoneNumber: 5550123791,
  },
  {
    id: 52,
    firstName: "Jordan",
    lastName: "Turner",
    city: "St. Louis",
    degree: "MD",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 16,
    phoneNumber: 5553456824,
  },
  {
    id: 53,
    firstName: "Christina",
    lastName: "Phillips",
    city: "Riverside",
    degree: "PhD",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 7,
    phoneNumber: 5556789157,
  },
  {
    id: 54,
    firstName: "Nathan",
    lastName: "Campbell",
    city: "Pittsburgh",
    degree: "MSW",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 4,
    phoneNumber: 5559012480,
  },
  {
    id: 55,
    firstName: "Rebecca",
    lastName: "Parker",
    city: "Lexington",
    degree: "MA",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 14,
    phoneNumber: 5552345813,
  },
  {
    id: 56,
    firstName: "Jacob",
    lastName: "Evans",
    city: "Anchorage",
    degree: "PhD",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 10,
    phoneNumber: 5555678146,
  },
  {
    id: 57,
    firstName: "Victoria",
    lastName: "Edwards",
    city: "Stockton",
    degree: "MSW",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 6,
    phoneNumber: 5558901479,
  },
  {
    id: 58,
    firstName: "Peter",
    lastName: "Collins",
    city: "Cincinnati",
    degree: "MD",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 18,
    phoneNumber: 5551234702,
  },
  {
    id: 59,
    firstName: "Danielle",
    lastName: "Stewart",
    city: "St. Paul",
    degree: "PhD",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 9,
    phoneNumber: 5554567035,
  },
  {
    id: 60,
    firstName: "Anthony",
    lastName: "Sanchez",
    city: "Toledo",
    degree: "MSW",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 13,
    phoneNumber: 5557890368,
  },
];

export { advocateData };
